AI:
  override_refbox_defending_side:
    type: "bool"
    default: false
    description: >-
        Overrides the defending side provided by refbox, 
        with defending_positive_side parameter
  defending_positive_side:
    type: "bool"
    default: true
    description: >-
        Positive if selected, Negative if unselected
  override_refbox_friendly_team_color:
    type: "bool"
    default: false
    description: >-
        Overrides the team color provided by refbox, 
        with friendly_color_yellow parameter
  friendly_color_yellow:
    type: "bool"
    default: true
    description: >-
        Yellow if selected, Blue if unselected

